role: local

host: 0.0.0.0
port: 4444
sessionIdleTimeout: 60
maxSessions: 5

fileServer:
  root: .

registerTo: http://localhost:5555

drivers:
  - browserName: chrome
    browserVersion: stable
    maxSessions: 2
    webdriver:
      path: ./chromedriver.exe

  - browserName: MicrosoftEdge
    maxSessions: 2
    webdriver:
      path: ./msedgedriver.exe

  - browserName: firefox
    maxSessions: 2
    webdriver:
      path: ./geckodriver.exe

  - browserName: safari
    maxSessions: 1
    webdriver:
      path: safaridriver

provision:
  tasks:
    - download: https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
      cmds:
        - open -W {download_file_path}
        - cp -r "/Volumes/Google Chrome/Google Chrome.app" /Applications/
    - cmds:
        - echo 'hello world'
      neverSkip: true
